# Generated by Django 3.2.7 on 2021-09-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='captions',
            new_name='caption',
        ),
    ]
